/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/nextripv2/agencies": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["Agency"][];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/nextripv2/routes": {
    get: {
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["Route"][];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/nextripv2/directions/{route_id}": {
    get: {
      parameters: {
        path: {
          route_id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["Direction"][];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/nextripv2/stops/{route_id}/{direction_id}": {
    get: {
      parameters: {
        path: {
          route_id: string;
          direction_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["Place"][];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/nextripv2/{stop_id}": {
    get: {
      parameters: {
        path: {
          stop_id: number;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["NexTripResult"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/nextripv2/{route_id}/{direction_id}/{place_code}": {
    get: {
      parameters: {
        path: {
          route_id: string;
          direction_id: number;
          place_code: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["NexTripResult"];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
  "/nextripv2/vehicles/{route_id}": {
    get: {
      parameters: {
        path: {
          route_id: string;
        };
      };
      responses: {
        /** Success */
        200: {
          content: {
            "application/json": components["schemas"]["Vehicle"][];
          };
        };
        /** Bad Request */
        400: {
          content: {
            "application/json": components["schemas"]["ProblemDetails"];
          };
        };
        /** Server Error */
        500: unknown;
      };
    };
  };
}

export interface components {
  schemas: {
    Agency: {
      /** Format: int32 */
      agency_id?: number;
      agency_name?: string | null;
    };
    AlertMessage: {
      stop_closed?: boolean;
      alert_text?: string | null;
    };
    Departure: {
      actual?: boolean;
      trip_id?: string | null;
      /** Format: int32 */
      stop_id?: number;
      departure_text?: string | null;
      /** Format: int64 */
      departure_time?: number;
      description?: string | null;
      gate?: string | null;
      route_id?: string | null;
      route_short_name?: string | null;
      /** Format: int32 */
      direction_id?: number;
      direction_text?: string | null;
      terminal?: string | null;
      schedule_relationship?: string | null;
    };
    Direction: {
      /** Format: int32 */
      direction_id?: number;
      direction_name?: string | null;
    };
    NexTripResult: {
      stops?: components["schemas"]["Stop"][] | null;
      alerts?: components["schemas"]["AlertMessage"][] | null;
      departures?: components["schemas"]["Departure"][] | null;
    };
    Place: {
      place_code?: string | null;
      description?: string | null;
    };
    ProblemDetails: {
      type?: string | null;
      title?: string | null;
      /** Format: int32 */
      status?: number | null;
      detail?: string | null;
      instance?: string | null;
    } & { [key: string]: unknown };
    Route: {
      route_id?: string | null;
      /** Format: int32 */
      agency_id?: number;
      route_label?: string | null;
    };
    Stop: {
      /** Format: int32 */
      stop_id?: number;
      /** Format: double */
      latitude?: number;
      /** Format: double */
      longitude?: number;
      description?: string | null;
    };
    Vehicle: {
      trip_id?: string | null;
      /** Format: int32 */
      direction_id?: number;
      direction?: string | null;
      /** Format: int64 */
      location_time?: number;
      route_id?: string | null;
      terminal?: string | null;
      /** Format: float */
      latitude?: number;
      /** Format: float */
      longitude?: number;
      /** Format: float */
      bearing?: number;
      /** Format: double */
      odometer?: number;
      /** Format: float */
      speed?: number;
    };
  };
}

export interface operations {}

export interface external {}
